# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Ключеві слова', 'verbose_name_plural': 'Ключеві слова'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новини', 'verbose_name_plural': 'Новини'},
        ),
    ]
