# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 06:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrip', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='about_photo')),
            ],
        ),
    ]
