# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Інформація про лікаря', 'verbose_name_plural': 'Інформація про лікаря'},
        ),
        migrations.AlterModelOptions(
            name='aboutmed',
            options={'verbose_name': 'Інформація про медсестру', 'verbose_name_plural': 'Інформація про медсестру'},
        ),
        migrations.AlterModelOptions(
            name='seasonnote',
            options={'verbose_name': 'Сезонні нотатки', 'verbose_name_plural': 'Сезонні нотатки'},
        ),
    ]
