# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
    ]
